[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "uuid"] }
uuid = { version = "1", features = ["v4", "serde"] }
